-- KANTON — seed com o catálogo real extraído do Instagram @usekanton.
-- Rode depois de 0001_schema.sql. Reexecutável: atualiza o que já existe.
-- As fotos ficam em /public/produtos no repositório; envios novos pelo
-- painel vão para o bucket produtos do Storage.

insert into categorias (nome, slug, ordem, ativo) values
  ('Tênis', 'tenis', 1, true),
  ('Alfaiataria', 'alfaiataria', 2, true),
  ('Jaquetas & Casacos', 'jaquetas', 3, true),
  ('Jeans', 'jeans', 4, true),
  ('Vestidos', 'vestidos', 5, true),
  ('Fitness', 'fitness', 6, true),
  ('Lingerie & Pijamas', 'lingerie', 7, true),
  ('Camisas de Time', 'camisas-de-time', 8, true)
on conflict (slug) do update set nome = excluded.nome, ordem = excluded.ordem;

insert into produtos (codigo, nome, slug, descricao, marca, preco, preco_promocional, categoria_id, tamanhos, cores, destaque, ativo, ordem) values
  ('KTN-0001', 'New Balance 9060 branco e cinza', 'new-balance-9060-branco-e-cinza', null, 'New Balance', 899.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['branco','cinza']::text[], true, true, 0),
  ('KTN-0002', 'New Balance 9060 creme e cinza', 'new-balance-9060-creme-e-cinza', null, 'New Balance', 899.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['creme','cinza']::text[], false, true, 1),
  ('KTN-0003', 'New Balance 9060 creme e vinho', 'new-balance-9060-creme-e-vinho', null, 'New Balance', 899.9, 799.9, (select id from categorias where slug = 'tenis'), '{}'::text[], array['creme','vinho']::text[], true, true, 2),
  ('KTN-0004', 'New Balance 9060 marrom e creme', 'new-balance-9060-marrom-e-creme', null, 'New Balance', 899.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['marrom','creme']::text[], true, true, 3),
  ('KTN-0005', 'New Balance 9060 preto', 'new-balance-9060-preto', null, 'New Balance', 899.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['preto']::text[], false, true, 4),
  ('KTN-0006', 'New Balance 9060 preto e branco', 'new-balance-9060-preto-e-branco', null, 'New Balance', 899.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['preto','branco']::text[], false, true, 5),
  ('KTN-0007', 'New Balance bege e caramelo', 'new-balance-bege-e-caramelo', null, 'New Balance', 649.9, null, (select id from categorias where slug = 'tenis'), array['34','35','36','37','38','39']::text[], array['bege','caramelo']::text[], false, true, 6),
  ('KTN-0008', 'New Balance CT302 preto e branco', 'new-balance-ct302-preto-e-branco', null, 'New Balance', 699.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['preto','branco']::text[], false, true, 7),
  ('KTN-0009', 'Adidas Samba branco e preto', 'adidas-samba-branco-e-preto', null, 'Adidas', 749.9, 649.9, (select id from categorias where slug = 'tenis'), '{}'::text[], array['branco','preto']::text[], true, true, 8),
  ('KTN-0010', 'Adidas Campus creme e marrom', 'adidas-campus-creme-e-marrom', null, 'Adidas', 699.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['creme','marrom']::text[], true, true, 9),
  ('KTN-0011', 'Adidas azul e dourado', 'adidas-azul-e-dourado', null, 'Adidas', 499.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['azul','dourado']::text[], false, true, 10),
  ('KTN-0012', 'Adidas rosa e bronze', 'adidas-rosa-e-bronze', null, 'Adidas', 529.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['rosa','bronze']::text[], false, true, 11),
  ('KTN-0013', 'Louis Vuitton branco e caramelo', 'louis-vuitton-branco-e-caramelo', null, 'Louis Vuitton', 1290, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['branco','caramelo']::text[], true, true, 12),
  ('KTN-0014', 'Louis Vuitton azul e branco', 'louis-vuitton-azul-e-branco', null, 'Louis Vuitton', 1290, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['azul','branco']::text[], false, true, 13),
  ('KTN-0015', 'Nike Free cinza e coral', 'nike-free-cinza-e-coral', null, 'Nike', 559.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['cinza','coral']::text[], false, true, 14),
  ('KTN-0016', 'Nike Free preto e coral', 'nike-free-preto-e-coral', null, 'Nike', 559.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['preto','coral']::text[], false, true, 15),
  ('KTN-0017', 'Puma Suede preto e branco', 'puma-suede-preto-e-branco', null, 'Puma', 399.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['preto','branco']::text[], false, true, 16),
  ('KTN-0018', 'Puma plataforma preto', 'puma-plataforma-preto', null, 'Puma', 449.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['preto']::text[], false, true, 17),
  ('KTN-0019', 'Puma branco', 'puma-branco', null, 'Puma', 379.9, null, (select id from categorias where slug = 'tenis'), '{}'::text[], array['branco']::text[], false, true, 18),
  ('KTN-0020', 'Olimpikus corrida branco e rosa', 'olimpikus-corrida-branco-e-rosa', null, 'Olimpikus', 329.9, 279.9, (select id from categorias where slug = 'tenis'), '{}'::text[], array['branco','rosa']::text[], false, true, 19),
  ('KTN-0021', 'Conjunto de alfaiataria off-white', 'conjunto-de-alfaiataria-off-white', null, null, 429.9, null, (select id from categorias where slug = 'alfaiataria'), '{}'::text[], array['off-white']::text[], true, true, 20),
  ('KTN-0022', 'Conjunto de alfaiataria marrom escuro', 'conjunto-de-alfaiataria-marrom-escuro', null, null, 429.9, null, (select id from categorias where slug = 'alfaiataria'), '{}'::text[], array['marrom']::text[], false, true, 21),
  ('KTN-0023', 'Conjunto de alfaiataria taupe', 'conjunto-de-alfaiataria-taupe', null, null, 429.9, null, (select id from categorias where slug = 'alfaiataria'), '{}'::text[], array['taupe']::text[], true, true, 22),
  ('KTN-0024', 'Conjunto camisa e calça bege', 'conjunto-camisa-e-calca-bege', null, null, 389.9, null, (select id from categorias where slug = 'alfaiataria'), '{}'::text[], array['bege']::text[], false, true, 23),
  ('KTN-0025', 'Conjunto colete e saia caramelo', 'conjunto-colete-e-saia-caramelo', null, null, 359.9, null, (select id from categorias where slug = 'alfaiataria'), '{}'::text[], array['caramelo']::text[], false, true, 24),
  ('KTN-0026', 'Blusa de cetim bege manga bufante', 'blusa-de-cetim-bege-manga-bufante', null, null, 159.9, null, (select id from categorias where slug = 'alfaiataria'), '{}'::text[], array['bege']::text[], false, true, 25),
  ('KTN-0027', 'Body de renda preto gola alta', 'body-de-renda-preto-gola-alta', null, null, 139.9, null, (select id from categorias where slug = 'alfaiataria'), '{}'::text[], array['preto']::text[], false, true, 26),
  ('KTN-0028', 'Body de renda azul-marinho', 'body-de-renda-azul-marinho', null, null, 139.9, null, (select id from categorias where slug = 'alfaiataria'), '{}'::text[], array['azul-marinho']::text[], false, true, 27),
  ('KTN-0029', 'Jaqueta de couro caramelo', 'jaqueta-de-couro-caramelo', null, null, 599.9, 499.9, (select id from categorias where slug = 'jaquetas'), '{}'::text[], array['caramelo']::text[], true, true, 28),
  ('KTN-0030', 'Jaqueta jeans clara', 'jaqueta-jeans-clara', null, null, 289.9, null, (select id from categorias where slug = 'jeans'), '{}'::text[], array['azul claro']::text[], false, true, 29),
  ('KTN-0031', 'Vestido marrom manga longa', 'vestido-marrom-manga-longa', null, null, 249.9, null, (select id from categorias where slug = 'vestidos'), '{}'::text[], array['marrom']::text[], true, true, 30),
  ('KTN-0032', 'Vestido plissado off-white', 'vestido-plissado-off-white', null, null, 229.9, null, (select id from categorias where slug = 'vestidos'), '{}'::text[], array['off-white']::text[], false, true, 31),
  ('KTN-0033', 'Conjunto camisa e saia marrom', 'conjunto-camisa-e-saia-marrom', null, null, 269.9, null, (select id from categorias where slug = 'vestidos'), '{}'::text[], array['marrom']::text[], false, true, 32),
  ('KTN-0034', 'Legging Alo preta cintura alta', 'legging-alo-preta-cintura-alta', null, 'Alo', 289.9, null, (select id from categorias where slug = 'fitness'), '{}'::text[], array['preto']::text[], false, true, 33),
  ('KTN-0035', 'Legging Alo rosa', 'legging-alo-rosa', null, 'Alo', 289.9, null, (select id from categorias where slug = 'fitness'), '{}'::text[], array['rosa']::text[], false, true, 34),
  ('KTN-0036', 'Legging Alo cores sortidas', 'legging-alo-cores-sortidas', null, 'Alo', 289.9, null, (select id from categorias where slug = 'fitness'), '{}'::text[], array['rosa','lilás','preto','creme']::text[], false, true, 35),
  ('KTN-0037', 'Camiseta Nike Dri-FIT preta', 'camiseta-nike-dri-fit-preta', null, 'Nike', 179.9, null, (select id from categorias where slug = 'fitness'), '{}'::text[], array['preto']::text[], false, true, 36),
  ('KTN-0038', 'Short Adidas magenta', 'short-adidas-magenta', null, 'Adidas', 199.9, null, (select id from categorias where slug = 'fitness'), '{}'::text[], array['magenta']::text[], false, true, 37),
  ('KTN-0039', 'Pijama de renda vermelho', 'pijama-de-renda-vermelho', null, null, 149.9, null, (select id from categorias where slug = 'lingerie'), '{}'::text[], array['vermelho']::text[], true, true, 38),
  ('KTN-0040', 'Camisola de cetim off-white', 'camisola-de-cetim-off-white', null, null, 129.9, null, (select id from categorias where slug = 'lingerie'), '{}'::text[], array['off-white']::text[], false, true, 39),
  ('KTN-0041', 'Pijama de cetim preto', 'pijama-de-cetim-preto', null, null, 139.9, null, (select id from categorias where slug = 'lingerie'), '{}'::text[], array['preto']::text[], false, true, 40),
  ('KTN-0042', 'Pijama de cetim rosa', 'pijama-de-cetim-rosa', null, null, 139.9, null, (select id from categorias where slug = 'lingerie'), '{}'::text[], array['rosa']::text[], false, true, 41),
  ('KTN-0043', 'Robe de renda rosa', 'robe-de-renda-rosa', null, null, 169.9, null, (select id from categorias where slug = 'lingerie'), '{}'::text[], array['rosa']::text[], false, true, 42),
  ('KTN-0044', 'Camisa do Brasil amarela', 'camisa-do-brasil-amarela', null, 'Nike', 199.9, null, (select id from categorias where slug = 'camisas-de-time'), '{}'::text[], array['amarelo']::text[], false, true, 43)
on conflict (slug) do update set
  nome = excluded.nome, descricao = excluded.descricao, marca = excluded.marca,
  preco = excluded.preco, preco_promocional = excluded.preco_promocional,
  categoria_id = excluded.categoria_id, tamanhos = excluded.tamanhos,
  cores = excluded.cores, destaque = excluded.destaque, ativo = excluded.ativo,
  ordem = excluded.ordem;

-- imagens: refaz a lista de cada peça
delete from produto_imagens where produto_id in (select id from produtos where slug in ('new-balance-9060-branco-e-cinza', 'new-balance-9060-creme-e-cinza', 'new-balance-9060-creme-e-vinho', 'new-balance-9060-marrom-e-creme', 'new-balance-9060-preto', 'new-balance-9060-preto-e-branco', 'new-balance-bege-e-caramelo', 'new-balance-ct302-preto-e-branco', 'adidas-samba-branco-e-preto', 'adidas-campus-creme-e-marrom', 'adidas-azul-e-dourado', 'adidas-rosa-e-bronze', 'louis-vuitton-branco-e-caramelo', 'louis-vuitton-azul-e-branco', 'nike-free-cinza-e-coral', 'nike-free-preto-e-coral', 'puma-suede-preto-e-branco', 'puma-plataforma-preto', 'puma-branco', 'olimpikus-corrida-branco-e-rosa', 'conjunto-de-alfaiataria-off-white', 'conjunto-de-alfaiataria-marrom-escuro', 'conjunto-de-alfaiataria-taupe', 'conjunto-camisa-e-calca-bege', 'conjunto-colete-e-saia-caramelo', 'blusa-de-cetim-bege-manga-bufante', 'body-de-renda-preto-gola-alta', 'body-de-renda-azul-marinho', 'jaqueta-de-couro-caramelo', 'jaqueta-jeans-clara', 'vestido-marrom-manga-longa', 'vestido-plissado-off-white', 'conjunto-camisa-e-saia-marrom', 'legging-alo-preta-cintura-alta', 'legging-alo-rosa', 'legging-alo-cores-sortidas', 'camiseta-nike-dri-fit-preta', 'short-adidas-magenta', 'pijama-de-renda-vermelho', 'camisola-de-cetim-off-white', 'pijama-de-cetim-preto', 'pijama-de-cetim-rosa', 'robe-de-renda-rosa', 'camisa-do-brasil-amarela'));
insert into produto_imagens (produto_id, url, alt, ordem) values
  ((select id from produtos where slug = 'new-balance-9060-branco-e-cinza'), '/produtos/new-balance-9060-branco-e-cinza.webp', 'New Balance 9060 branco e cinza — New Balance, KANTON', 0),
  ((select id from produtos where slug = 'new-balance-9060-creme-e-cinza'), '/produtos/new-balance-9060-creme-e-cinza.webp', 'New Balance 9060 creme e cinza — New Balance, KANTON', 0),
  ((select id from produtos where slug = 'new-balance-9060-creme-e-vinho'), '/produtos/new-balance-9060-creme-e-vinho.webp', 'New Balance 9060 creme e vinho — New Balance, KANTON', 0),
  ((select id from produtos where slug = 'new-balance-9060-marrom-e-creme'), '/produtos/new-balance-9060-marrom-e-creme.webp', 'New Balance 9060 marrom e creme — New Balance, KANTON', 0),
  ((select id from produtos where slug = 'new-balance-9060-preto'), '/produtos/new-balance-9060-preto.webp', 'New Balance 9060 preto — New Balance, KANTON', 0),
  ((select id from produtos where slug = 'new-balance-9060-preto-e-branco'), '/produtos/new-balance-9060-preto-e-branco.webp', 'New Balance 9060 preto e branco — New Balance, KANTON', 0),
  ((select id from produtos where slug = 'new-balance-bege-e-caramelo'), '/produtos/new-balance-bege-e-caramelo.webp', 'New Balance bege e caramelo — New Balance, KANTON', 0),
  ((select id from produtos where slug = 'new-balance-ct302-preto-e-branco'), '/produtos/new-balance-ct302-preto-e-branco.webp', 'New Balance CT302 preto e branco — New Balance, KANTON', 0),
  ((select id from produtos where slug = 'adidas-samba-branco-e-preto'), '/produtos/adidas-samba-branco-e-preto.webp', 'Adidas Samba branco e preto — Adidas, KANTON', 0),
  ((select id from produtos where slug = 'adidas-campus-creme-e-marrom'), '/produtos/adidas-campus-creme-e-marrom.webp', 'Adidas Campus creme e marrom — Adidas, KANTON', 0),
  ((select id from produtos where slug = 'adidas-azul-e-dourado'), '/produtos/adidas-azul-e-dourado.webp', 'Adidas azul e dourado — Adidas, KANTON', 0),
  ((select id from produtos where slug = 'adidas-rosa-e-bronze'), '/produtos/adidas-rosa-e-bronze.webp', 'Adidas rosa e bronze — Adidas, KANTON', 0),
  ((select id from produtos where slug = 'louis-vuitton-branco-e-caramelo'), '/produtos/louis-vuitton-branco-e-caramelo.webp', 'Louis Vuitton branco e caramelo — Louis Vuitton, KANTON', 0),
  ((select id from produtos where slug = 'louis-vuitton-azul-e-branco'), '/produtos/louis-vuitton-azul-e-branco.webp', 'Louis Vuitton azul e branco — Louis Vuitton, KANTON', 0),
  ((select id from produtos where slug = 'nike-free-cinza-e-coral'), '/produtos/nike-free-cinza-e-coral.webp', 'Nike Free cinza e coral — Nike, KANTON', 0),
  ((select id from produtos where slug = 'nike-free-preto-e-coral'), '/produtos/nike-free-preto-e-coral.webp', 'Nike Free preto e coral — Nike, KANTON', 0),
  ((select id from produtos where slug = 'puma-suede-preto-e-branco'), '/produtos/puma-suede-preto-e-branco.webp', 'Puma Suede preto e branco — Puma, KANTON', 0),
  ((select id from produtos where slug = 'puma-plataforma-preto'), '/produtos/puma-plataforma-preto.webp', 'Puma plataforma preto — Puma, KANTON', 0),
  ((select id from produtos where slug = 'puma-branco'), '/produtos/puma-branco.webp', 'Puma branco — Puma, KANTON', 0),
  ((select id from produtos where slug = 'olimpikus-corrida-branco-e-rosa'), '/produtos/olimpikus-corrida-branco-e-rosa.webp', 'Olimpikus corrida branco e rosa — Olimpikus, KANTON', 0),
  ((select id from produtos where slug = 'conjunto-de-alfaiataria-off-white'), '/produtos/conjunto-de-alfaiataria-off-white.webp', 'Conjunto de alfaiataria off-white, KANTON', 0),
  ((select id from produtos where slug = 'conjunto-de-alfaiataria-marrom-escuro'), '/produtos/conjunto-de-alfaiataria-marrom-escuro.webp', 'Conjunto de alfaiataria marrom escuro, KANTON', 0),
  ((select id from produtos where slug = 'conjunto-de-alfaiataria-taupe'), '/produtos/conjunto-de-alfaiataria-taupe.webp', 'Conjunto de alfaiataria taupe, KANTON', 0),
  ((select id from produtos where slug = 'conjunto-camisa-e-calca-bege'), '/produtos/conjunto-camisa-e-calca-bege.webp', 'Conjunto camisa e calça bege, KANTON', 0),
  ((select id from produtos where slug = 'conjunto-colete-e-saia-caramelo'), '/produtos/conjunto-colete-e-saia-caramelo.webp', 'Conjunto colete e saia caramelo, KANTON', 0),
  ((select id from produtos where slug = 'blusa-de-cetim-bege-manga-bufante'), '/produtos/blusa-de-cetim-bege-manga-bufante.webp', 'Blusa de cetim bege manga bufante, KANTON', 0),
  ((select id from produtos where slug = 'body-de-renda-preto-gola-alta'), '/produtos/body-de-renda-preto-gola-alta.webp', 'Body de renda preto gola alta, KANTON', 0),
  ((select id from produtos where slug = 'body-de-renda-azul-marinho'), '/produtos/body-de-renda-azul-marinho.webp', 'Body de renda azul-marinho, KANTON', 0),
  ((select id from produtos where slug = 'jaqueta-de-couro-caramelo'), '/produtos/jaqueta-de-couro-caramelo.webp', 'Jaqueta de couro caramelo, KANTON', 0),
  ((select id from produtos where slug = 'jaqueta-jeans-clara'), '/produtos/jaqueta-jeans-clara.webp', 'Jaqueta jeans clara, KANTON', 0),
  ((select id from produtos where slug = 'vestido-marrom-manga-longa'), '/produtos/vestido-marrom-manga-longa.webp', 'Vestido marrom manga longa, KANTON', 0),
  ((select id from produtos where slug = 'vestido-plissado-off-white'), '/produtos/vestido-plissado-off-white.webp', 'Vestido plissado off-white, KANTON', 0),
  ((select id from produtos where slug = 'conjunto-camisa-e-saia-marrom'), '/produtos/conjunto-camisa-e-saia-marrom.webp', 'Conjunto camisa e saia marrom, KANTON', 0),
  ((select id from produtos where slug = 'legging-alo-preta-cintura-alta'), '/produtos/legging-alo-preta-cintura-alta.webp', 'Legging Alo preta cintura alta — Alo, KANTON', 0),
  ((select id from produtos where slug = 'legging-alo-rosa'), '/produtos/legging-alo-rosa.webp', 'Legging Alo rosa — Alo, KANTON', 0),
  ((select id from produtos where slug = 'legging-alo-cores-sortidas'), '/produtos/legging-alo-cores-sortidas.webp', 'Legging Alo cores sortidas — Alo, KANTON', 0),
  ((select id from produtos where slug = 'camiseta-nike-dri-fit-preta'), '/produtos/camiseta-nike-dri-fit-preta.webp', 'Camiseta Nike Dri-FIT preta — Nike, KANTON', 0),
  ((select id from produtos where slug = 'short-adidas-magenta'), '/produtos/short-adidas-magenta.webp', 'Short Adidas magenta — Adidas, KANTON', 0),
  ((select id from produtos where slug = 'pijama-de-renda-vermelho'), '/produtos/pijama-de-renda-vermelho.webp', 'Pijama de renda vermelho, KANTON', 0),
  ((select id from produtos where slug = 'camisola-de-cetim-off-white'), '/produtos/camisola-de-cetim-off-white.webp', 'Camisola de cetim off-white, KANTON', 0),
  ((select id from produtos where slug = 'pijama-de-cetim-preto'), '/produtos/pijama-de-cetim-preto.webp', 'Pijama de cetim preto, KANTON', 0),
  ((select id from produtos where slug = 'pijama-de-cetim-rosa'), '/produtos/pijama-de-cetim-rosa.webp', 'Pijama de cetim rosa, KANTON', 0),
  ((select id from produtos where slug = 'robe-de-renda-rosa'), '/produtos/robe-de-renda-rosa.webp', 'Robe de renda rosa, KANTON', 0),
  ((select id from produtos where slug = 'camisa-do-brasil-amarela'), '/produtos/camisa-do-brasil-amarela.webp', 'Camisa do Brasil amarela — Nike, KANTON', 0);

insert into config (chave, valor) values
  ('whatsapp', '5532991169200'),
  ('instagram', 'usekanton'),
  ('cidade', 'Santos Dumont | MG'),
  ('aviso_topo', 'Frete grátis acima de R$ 299 para todo o Brasil | Até 6x sem juros no cartão | Retirada na loja em Santos Dumont, sem custo | Primeira troca por nossa conta'),
  ('frase_hero', 'Tênis, alfaiataria e multimarcas'),
  ('endereco', ''),
  ('horario', '')
on conflict (chave) do update set valor = excluded.valor;
